# Generated by Django 4.1 on 2022-08-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="craeted_by",
            new_name="created_by",
        ),
    ]
