# Generated by Django 4.1 on 2022-08-14 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0002_rename_craeted_by_poll_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="poll",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="polls.poll",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="voted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
