# Generated by Django 4.1 on 2022-08-14 16:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0003_alter_vote_poll_alter_vote_voted_by"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("poll", "voted_by")},
        ),
    ]
