# Generated by Django 4.1 on 2022-08-19 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="owner",
            new_name="user",
        ),
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="notes.tag"),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("user", "name")},
        ),
    ]
