# Generated by Django 4.1 on 2022-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_rename_owner_note_user_note_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
