# Generated by Django 4.1 on 2022-08-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_note_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(related_name="notes", to="notes.tag"),
        ),
    ]
